ALTER TABLE sensory_trace ADD COLUMN IF NOT EXISTS exclude_from_reflection BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE episodes ADD COLUMN IF NOT EXISTS exclude_from_reflection BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE concepts ADD COLUMN IF NOT EXISTS exclude_from_reflection BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE entities ADD COLUMN IF NOT EXISTS exclude_from_reflection BOOLEAN NOT NULL DEFAULT FALSE;
