#!/usr/bin/env node
/**
 * Promotes a single skill candidate by DB id.
 * Runnable directly via: npx tsx packages/usme-core/src/scripts/promote-candidate.ts <id>
 *
 * Args:
 *   <id>        Numeric candidate ID (positional, optional if --pick is given)
 *   --pick N    Pick the Nth candidate (1-based) from the sorted list (confidence DESC)
 *
 * The script is fully self-contained: it writes SKILL.md, computes an embedding,
 * and updates the DB — no external event firing required.
 */

import fs from "node:fs";
import path from "node:path";
import {
  getPool,
  closePool,
  getPromoteCandidates,
  getEnrichContext,
  embedText,
} from "../index.js";

// ── SKILL.md builder ───────────────────────────────────────────────────────

function buildSkillMd(ctx: Awaited<ReturnType<typeof getEnrichContext>>): string {
  const episodesSection =
    ctx.sourceEpisodes.length > 0
      ? ctx.sourceEpisodes
          .map(
            (e) =>
              `- **Episode ${e.id}** (${String(e.createdAt).split("T")[0]}): ${e.summary}`,
          )
          .join("\n")
      : "_No source episodes recorded. Manual review recommended._";

  const conceptsSection =
    ctx.relatedConcepts.length > 0
      ? ctx.relatedConcepts.map((c) => `- **${c.name}**: ${c.summary ?? ""}`).join("\n")
      : "_No related concepts found._";

  const stepsSection =
    ctx.sourceEpisodes.length > 0
      ? ctx.sourceEpisodes
          .slice(0, 3)
          .map(
            (e, i) =>
              `${i + 1}. _(from episode ${e.id})_ ${e.summary.slice(0, 300)}`,
          )
          .join("\n\n")
      : "_Steps not yet derived. Populate from source episodes when available._";

  return `# ${ctx.name}

> Confidence: ${Number(ctx.confidence).toFixed(2)} | Tier: ${ctx.qualityTier} | Candidate ID: ${ctx.candidateId}

## When to Use This Skill

${ctx.description ?? "_No description provided._"}

**Trigger pattern:** ${ctx.triggerPattern ?? "_Not specified._"}

## Prerequisites

_Review source episodes below to identify required tools, env vars, and context._

${conceptsSection}

## Steps

_Derived from source episodes. Verify commands before use._

${stepsSection}

## Failure Modes

| Failure | Cause | Recovery |
|---------|-------|----------|
| _Not yet documented_ | _See source episodes_ | _Manual review required_ |

## Verification

_Add specific checks that confirm the skill completed successfully._

## Best Practices

_To be populated from documentation and experience._

---

## Source Episodes (grounding material)

${episodesSection}

<!-- Generated by usme promote-candidate.ts — enrich with lived experience -->
`;
}

// ── Main ───────────────────────────────────────────────────────────────────

async function main() {
  const args = process.argv.slice(2);

  // Parse --pick N
  let pickIndex: number | undefined;
  const pickIdx = args.indexOf("--pick");
  if (pickIdx !== -1) {
    const pickVal = args[pickIdx + 1];
    if (!pickVal || isNaN(Number(pickVal))) {
      process.stderr.write("--pick requires a numeric argument\n");
      process.exit(1);
    }
    pickIndex = parseInt(pickVal, 10);
    if (pickIndex < 1) {
      process.stderr.write("--pick N must be >= 1\n");
      process.exit(1);
    }
  }

  // Resolve candidate id
  const pool = getPool();
  let candidateId: number;

  try {
    if (pickIndex !== undefined) {
      // Fetch sorted list and pick by 1-based position
      const all = await getPromoteCandidates(
        { forceAll: true, includeDrafts: true },
        pool,
      );
      if (pickIndex > all.length) {
        process.stderr.write(
          `--pick ${pickIndex} is out of range. ${all.length} candidate(s) available (1–${all.length}).\n`,
        );
        process.exit(1);
      }
      candidateId = all[pickIndex - 1].id;
    } else {
      const idStr = args.find((a) => !a.startsWith("-"));
      if (!idStr || isNaN(Number(idStr))) {
        process.stderr.write(
          "Usage: promote-candidate.ts <numeric-candidate-id>\n       promote-candidate.ts --pick N\n",
        );
        process.exit(1);
      }
      candidateId = parseInt(idStr, 10);
    }

    // Verify candidate exists
    const candidates = await getPromoteCandidates(
      { forceAll: true, includeDrafts: true, id: candidateId },
      pool,
    );
    if (candidates.length === 0) {
      process.stderr.write(`Candidate ${candidateId} not found.\n`);
      process.exit(1);
    }
    const candidate = candidates[0];

    const skillSlug = candidate.name
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "");
    const skillPath = `/home/alex/ai/projects/.openclaw/workspace-rufus/skills/${skillSlug}/SKILL.md`;

    // ── Transaction: INSERT skills + UPDATE skill_candidates ──────────────
    const client = await pool.connect();
    let skillId: string;

    try {
      await client.query("BEGIN");

      // Mark candidate accepted
      await client.query(
        `UPDATE skill_candidates
         SET approval_status = 'accepted', accepted = true, accepted_at = NOW(), updated_at = NOW()
         WHERE id = $1`,
        [candidate.id],
      );

      // Insert into skills
      const { rows } = await client.query<{ id: string }>(
        `INSERT INTO skills
           (name, description, status, skill_path, source_episode_ids, teachability,
            promoted_at, source_candidate_id, generation_notes, metadata)
         VALUES ($1, $2, 'active', $3, $4, $5, NOW(), $6, $7, $8)
         ON CONFLICT (name) DO NOTHING
         RETURNING id`,
        [
          candidate.name,
          candidate.description ?? null,
          skillPath,
          candidate.source_episode_ids ?? null,
          candidate.confidence,
          candidate.id,
          JSON.stringify({ from_candidate: candidate.id, quality_tier: candidate.quality_tier }),
          "{}",
        ],
      );

      if (rows.length === 0) {
        await client.query("ROLLBACK");
        process.stderr.write(
          `A skill named "${candidate.name}" already exists — skipping insert.\n`,
        );
        process.exit(1);
      }

      skillId = rows[0].id;

      // Link candidate to the new skill; mark enrichment pending-write
      await client.query(
        `UPDATE skill_candidates
         SET promoted_skill_id = $2, enrichment_status = 'pending', updated_at = NOW()
         WHERE id = $1`,
        [candidate.id, skillId],
      );

      await client.query("COMMIT");
    } catch (err) {
      await client.query("ROLLBACK");
      throw err;
    } finally {
      client.release();
    }

    // ── Enrichment (outside transaction — recoverable on re-run) ──────────

    // Build context and SKILL.md content
    const enrichCtx = await getEnrichContext(candidate.id, pool);
    const skillContent = buildSkillMd(enrichCtx);

    // Write SKILL.md to disk
    const skillDir = path.dirname(skillPath);
    fs.mkdirSync(skillDir, { recursive: true });
    fs.writeFileSync(skillPath, skillContent, "utf-8");
    const lineCount = skillContent.split("\n").length;

    // Compute embedding
    let embeddingStored = false;
    const openaiKey = process.env.OPENAI_API_KEY ?? "";
    if (openaiKey) {
      try {
        const vec = await embedText(skillContent, openaiKey);
        // Store vector in pgvector format: '[x,x,x,...]'
        const vecLiteral = `[${vec.join(",")}]`;
        await pool.query(
          `UPDATE skills SET embedding = $2::vector WHERE id = $1`,
          [skillId, vecLiteral],
        );
        embeddingStored = true;
      } catch (embedErr) {
        const msg = embedErr instanceof Error ? embedErr.message : String(embedErr);
        process.stderr.write(`Warning: embedding failed (${msg}). Re-run to retry.\n`);
      }
    } else {
      process.stderr.write("Warning: OPENAI_API_KEY not set — embedding skipped.\n");
    }

    // Mark enrichment complete
    await pool.query(
      `UPDATE skill_candidates
       SET enrichment_status = 'complete', updated_at = NOW()
       WHERE id = $1`,
      [candidate.id],
    );

    process.stdout.write(
      `✓ Promoted "${candidate.name}"
  skill id   : ${skillId}
  file path  : ${skillPath}
  line count : ${lineCount}
  embedding  : ${embeddingStored ? "stored" : "skipped (no OPENAI_API_KEY)"}
`,
    );
  } finally {
    await closePool();
  }
}

main().catch((err) => {
  process.stderr.write(`Error: ${err.message}\n`);
  process.exit(1);
});
